### ISSUE TITLE
Typo in contribution guide

### ISSUE THREAD

**Issue by SJaffa** [popelier-group/ichor#57]
**Describe the bug**
In `CONTRIBUTING.md` on hte last line it says:

`An requests or issues or issues with the code `

**Expected behavior**

Should be "An**y** requests or **bugs** or issues with the code" ?

**Comment by ej159** [comment]
This should be fixed in PR #58

**Comment by ej159** [comment]
> This should be fixed in PR #58

My bad. It's not. Yet...

**Comment by m-julian** [comment]
Thanks!
