### ISSUE TITLE
Graph in GP example has no axis labels

### ISSUE THREAD

**Issue by SJaffa** [popelier-group/ichor#59]
**Describe the bug**
The example notebook in `docs/source/ichor_core_examples/simple_gp.ipynb` plits a graph showing good agreement between the traiing and test data but the axes are not labelled.

More description of the steps in the script would also be nice.

**Expected behavior**
All graphs have labels and units on axes

**Screenshots**
<img width="662" alt="Screenshot 2024-06-25 at 12 16 13" src="https://github.com/popelier-group/ichor/assets/13678317/67170994-fa79-44f2-90b1-60ba07262c40">

**Comment by m-julian** [comment]
Thanks for this! I have updated the notebook now to have references and more comments explaining what is happening. The updated notebook is up at https://ichor.readthedocs.io/en/latest/ichor_core_examples/simple_gp.html.

I've also added a link to the documentation on the side of the repo as you recommended, so it is easier to find.
