### ISSUE TITLE
Improve Documentation for GitBash users

### ISSUE THREAD

**Issue by HaleemaLimbada** [popelier-group/ichor#61]
**Describe the bug**
I was trying to set up ichor on windows 11 using gitbash, and had to follow different steps to what was in the documentation.

**To Reproduce**

**Expected behavior**

**Screenshots**
This is what happened when I followed the instructions:
![image](https://github.com/popelier-group/ichor/assets/157017172/a5529343-efad-4d9b-ab77-487b4ca107ce)

This is what it should be. I can create a PR for this if you want.
![image](https://github.com/popelier-group/ichor/assets/157017172/fb933679-52df-4c35-8473-45ef03165952)

**Additional context**

**Comment by m-julian** [comment]
Great, thanks for finding this! Could you add it to the installation rst file here https://github.com/popelier-group/ichor/blob/main/docs/source/installation.rst
