### ISSUE TITLE
List input/output file formats, compatible tools and possible workflows early in documentation

### ISSUE THREAD

**Issue by ej159** [popelier-group/ichor#64]
**Is your feature request related to a problem? Please describe.**

It would be really good to clearly show:

-  file formats for inputs to the tool(s)
-  file formats for output from the tool(s)
- other tools that are compatible/interoperable.

**Describe the solution you'd like**

- A list of file formats or, even better, a table on the first page of the documentation.
- A flowchart of what the tool does at a high level

**Describe alternatives you've considered**

These things are documented but one has to dig through the docs which makes it hard to conceptualise all the great things that the tools can do for me.

**Comment by m-julian** [comment]
Thanks, that would be a nice addition! I'll find some time to add a table with file formats along with some more exampes can run to get a feel of what the code can do.

**Comment by m-julian** [comment]
Implemented in https://github.com/popelier-group/ichor/pull/68
